language: ruby
rvm:
  - 2.3.0
cache: bundler
bundler_args: --without "production development"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test rake db:create
  - RAILS_ENV=test rake db:migrate
script:
  - bundle exec rake test